analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3441499,"name"\:"Sample - HR Web App \#3441499","teamId"\:3414977,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3476648,"autoIntegrate"\:false,"sampleProject"\:false,"accountId"\:null}
analytics.team={"id"\:3414977,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
